dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: dPn/wm4N7DAVk7UWIv9mKbH3uk72wgfjz0kHZhLkTxtVCZaK7JrjmKHzkgCk5iwQyH8LSMiisqmnNmdsJ9Gf0QV1JQ33WYTcbqwtCrEREx9nBcHyLYUnQeH9GwUm7ZSTBhjmMRHk4kZ7WpDVCsqQe3kmw7IBojvhxoo4pUBBguqVmb7m+95Z8xpr9zL50HetZ0emwRrCC8KYPHVy4PbpxGAabkbRNnCwMzCVvDsnoJPSpukhrnjLx5eTG4zeuk1X1pSGeBZINBTBZD44FDqa63AU/UL5Eaa+p7kLlJu3y2yEaQskF3RNCMPxo3oZqDm1jMw2wWwwfl3D9fuIORmPRYOakp+BgM+OlX2OMv6rASKiDeXs7Jer77h/f3/8ztkIxudC9ZQFLrTIJDpDMMaX+2SIgyuKcDW8Vem2N0BWdB/FVnk+AuaFfKrPw3FZe5Z+WEGkBCfWWdIwuJoRLVEEnLO24hZGG+imWYHuUQvZCsqws6wg452+w6yn0qyXfErWflR/a9u9/mzS5xsP9VEER/kEed/HsXWX4SBzefxxBgphpePqf6+1zaEoAv4qpixmh1DE6mMRBKByB+pX5KXnqUH/J08Tql44cLh/XnoPFgCOuklzAvka0wKd7RngkYLWNsiSa6tyFy+b4JYzGW9p/5grCIpQ8hFF5yorw99cHRA=
