FROM grafana/grafana:5.0.0

COPY provisioning/dashboards /etc/grafana/provisioning/dashboards
COPY provisioning/datasources /etc/grafana/provisioning/datasources
COPY dashboards /var/lib/grafana/dashboards
