apiVersion: 1

deleteDatasources:
  - name: 'Prometheus'
    orgId: 1

datasources:
  - name: 'Prometheus'
    isDefault: true
    orgId: 1
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: true
